name: EPG 大象新闻

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests==2.31.0 pytz==2024.1

    - name: Generate EPG
      run: |
          #ls 
          python jiaoben/epg_dxxw.py

    #- name: Commit changes
      #run: |
        #git add jiaoben/epg_cache/dxxw.xml
        #git add jiaoben/epg_cache/dxxw.txt
        #git -c user.name="GitHub Actions" -c user.email="actions@github.com" commit -m "Auto-update EPG $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
        #git push https://${{ github.actor}}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
    
    
    - name: 提交更新
      run: |
          cd $GITHUB_WORKSPACE/jiaoben/epg_cache
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update dxxw epg"
          git push
