name: get_zubo_fofa_py

on:
  schedule:
    - cron: '0 22 * * *'  # 每天 UTC 时间 1:00 执行，即北京时间 9:00

  workflow_dispatch:  # 手动触发

jobs:
  get_zubo_fofa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装扩展库
        run: pip install requests

      - name: 运行脚本
        run: |
          # 1. 确认文件真的在
          #ls -l ffmpeg
          # 2. 加可执行权限
          chmod +x ffmpeg
          # 3. 验证
          #./ffmpeg -version        # 必须能打印出版本号

          python jiaoben/get_zubo_fofa.py

      - name: Check workspace and epg directory
        run: |
          echo "Current workspace: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE/epg/

      - name: 缓存运行结果
        uses: actions/upload-artifact@v4
        with:
          name: cache
          path: .
          
      - name: 提交更新
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "PYTHON fofa"
          git push
