name: Scan m3u8 with cache IPs

on:
  workflow_dispatch:            # 手动触发
    inputs:
      template:
        description: "IP 模板，如 192.168"
        required: true
        default: "153.99"
      m3u8:
        description: "原始 m3u8 地址"
        required: true
        default: "https://hlslive-tx-cdn.ysp.cctv.cn/2022576702.m3u8"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      
      - run: pip install aiohttp
      
      - run: python jiaoben/scan_zhiboyuan.py ${{ github.event.inputs.template }} ${{ github.event.inputs.m3u8 }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: scan-result
          path: result.csv
